# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do|lane, options|
    setup_circle_ci
    @build_type = "Debug"
    @build_flavor = "Full"
    if not options.empty?
      @build_type = options[:release] ? "Release" : "Debug"
      @build_flavor = options[:demo] ? "Demo" : "Full"
    end
  end

  desc "Assemble Build"
  lane :assemble_build do |options|
    gradle(
      task: "assemble",
      build_type: @build_type,
      flavor: @build_flavor
    )
  end

  desc "Assemble Test Application"
  lane :assemble_test_application do
    gradle(
      task: "assemble",
      build_type: @build_type + "AndroidTest",
      flavor: @build_flavor
      )
  end

  desc "Assemble Build and Test Application"
  lane :assemble do
    assemble_build
    assemble_test_application
  end

  desc "Run unit tests"
  lane :unit_tests do |options|
    gradle(task: "test", build_type: @build_type)
  end

  desc "Submit a new Beta Build to Crashlytics"
  lane :beta do
    gradle(
      task: 'assemble',
      flavor: 'full',
      build_type: 'release'
    )
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  desc "Run instrumentation tests in Firebase Test Lab"
  lane :instrumentation_tests_testlab do
    run_tests_firebase_testlab(
      project_id: "devopsapp-d45e5",
      devices: [
        {
          model: "Nexus6P",
          version: "27"
        }
      ],
      app_apk: "app/build/outputs/apk/full/debug/app-full-debug.apk",
      android_test_apk: "app/build/outputs/apk/androidTest/full/debug/app-full-debug-androidTest.apk",
      delete_firebase_files: true
    )
  end
  
end
